django_web_app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    # ex: /polls/
    path('', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text

    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently'


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class Document(models.Model):
    title = models.CharField(max_length=80)
    # author = ?
    pub_date = models.DateTimeField('publish on')

    class Meta:
        abstract = True


class HowTo(Document):
    intro = models.CharField(max_length=500)
    tags = TaggableManager()

    def __str__(self):
        return '(title:"' + self.title + '"), (' + 'intro:"' + self.intro + '")'


class Step(models.Model):
    how_to = models.ForeignKey(HowTo, on_delete=models.CASCADE)
    title = models.CharField(max_length=80)
    markdown_content = models.CharField(max_length=5000) # chang the length


# class TheoreticalArticle(models.Model):
#     pass

polls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone

from .models import Choice, Question
from .models import HowTo, Step

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'howto_list'

    def get_queryset(self):
        """Return the last five published questions."""
        # return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
        return HowTo.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = HowTo
    template_name = 'polls/detail.html'
    context_object_name = 'current_how_to'

    def get_queryset(self):
        """Excludes any questions that aren't published yet."""
        return HowTo.objects.filter(id=13)

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
<h1>current_how_to.title: {{ current_how_to.title }}</h1>
<p>current_how_to.pub_date: {{ current_how_to.pub_date }}</p>
<p>current_how_to.intro: {{ current_how_to.intro }}</p>

{% for step in current_how_to.step_set.all %}
  <div class="step">
    <h1>step.title: {{ step.title }}</h1>
    <p>step.markdown_content: {{ step.markdown_content }}</p>
  </div>
{% endfor %}

polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if howto_list %}
    <ul>
    {% for how_to in howto_list %}
        <li><a href="{% url 'polls:detail' how_to.id %}">{{ how_to.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>